config/routes.rb
FormtasticNestedErrorsIssue::Application.routes.draw do
  root to: 'conversations#new'
  resources :conversations

end

app/models/conversation.rb
class Conversation
  include Mongoid::Document

  field :subject
  embeds_many :messages

  accepts_nested_attributes_for :messages

  validates :subject, presence: true
  validates_associated :messages
end

app/models/message.rb
class Message
  include Mongoid::Document
  field :body

  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  respond_to :html

  def new
    @conversation = Conversation.new
    @message      = @conversation.messages.build
  end

  def create
    @conversation = Conversation.new(params[:conversation])
    if @conversation.save
      redirect_to root_path, notice: 'conversation created!'
    else
      flash.now[:alert] = "Conversation not created. Errors: #{@conversation.errors.inspect}"
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/new.html.haml
%h1 New Conversation
= semantic_form_for @conversation, url: conversations_path do |form|
  = form.inputs do
    = form.input :subject
    = form.semantic_fields_for :messages, @message do |message|
      = message.input :body, as: :text
  = form.buttons do
    = form.commit_button label: 'Create Conversation'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FormtasticNestedErrorsIssue</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= "flash[notice] => #{flash[:notice]}" if flash[:notice] %>
  <%= "flash[alert] => #{flash[:alert]}" if flash[:alert] %>
<%= yield %>

</body>
</html>